export const SET_SMART = 'SET_SMART';
export const SET_SMART_SUCCESS = 'SET_SMART_SUCCESS';
export const SET_SMART_FAIL = 'SET_SMART_FAIL';

export const SET_PATIENT = 'SET_PATIENT';
export const SET_PATIENT_SUCCESS = 'SET_PATIENT_SUCCESS';
export const SET_PATIENT_FAIL = 'SET_PATIENT_FAIL';

export const SET_FORM = 'SET_FORM';
export const SET_FORM_SUCCESS = 'SET_FORM_SUCCESS';
export const SET_FORM_FAIL = 'SET_FORM_FAIL';
